### PR TITLE
Adding new conversions between temperature units and adding info to readme.md

### PR DESCRIPTION
**Pull request by ricardovelacy**

### CODE REVIEW

**Comment by mariovelandiac** [comment]
Ok, thank you, can you please add more info to readme.md?

**Review by mariovelandiac — CHANGES_REQUESTED** [review]
Add info in readme.md

**Comment by ricardovelacy** [comment]
It's done. I'll be waiting your response

**Review by mariovelandiac — APPROVED** [review]
Ok, thank you so much! 😛

**Pull request merged**
